#!/usr/bin/env python3
"""
New Tool Generator - Creates Python wrappers for external tools
This script generates a complete wrapper class based on tool metadata.

Author: Matt Pumphrey
Date: 3/16/2026
"""

import json
from datetime import datetime
from typing import Optional, Dict, Any


class NewToolGenerator:
    """Generates Python wrapper classes for new tools."""
    
    def __init__(self):
        self.version = "1.0"
        
    def generate_wrapper(self, tool_name: str, api_url: str, api_key_env_var: str) -> str:
        """Generate a complete Python wrapper class for the specified tool."""
        
        # Parse URL to extract domain and common patterns
        import re
        url_domain = self._extract_domain(api_url) if "://" in api_url else api_url
        
        wrapper_code = f'''#!/usr/bin/env python3
"""
{tool_name.capitalize()} API Wrapper
Auto-generated by New Tool Generator v{self.version}

This module provides a Python interface to the {tool_name.capitalize()} service.
Use this wrapper during the Harvesting stage to collect data from external sources.

Usage:
    from {tool_name}_wrapper import {{ToolName}}Wrapper
    
    wrapper = {{ToolName}}Wrapper(api_key="your_api_key")
    results = wrapper.search(query="example.com", limit=10)
"""

import os
import time
import logging
from typing import List, Dict, Any, Optional
import requests


# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class {{ToolName}}Wrapper:
    """
    Wrapper class for {tool_name.capitalize()} API.
    
    Attributes:
        api_key (str): The API key for authentication.
        base_url (str): The base URL of the API.
        rate_limit (float): Minimum seconds between requests (default 1).
    """
    
    DEFAULT_TIMEOUT = 30
    RATE_LIMIT = 1
    
    def __init__(self, api_key: Optional[str] = None, timeout: int = None):
        """
        Initialize the {tool_name.capitalize()} wrapper.
        
        Args:
            api_key: API key for authentication. If not provided, 
                     will attempt to read from environment variable.
            timeout: Request timeout in seconds (default: 30).
        """
        self.api_key = api_key or os.environ.get("{api_key_env_var}")
        
        if not self.api_key:
            raise ValueError(
                f"API key required. Set '{api_key_env_var}' environment variable "
                f"or pass it to the constructor."
            )
            
        self.base_url = "{api_url}"
        self.timeout = timeout or self.DEFAULT_TIMEOUT
        
        # Rate limiting state
        self._last_request_time = 0
        self.request_count = 0
        self.last_error: Optional[str] = None
        
        logger.info(f"{tool_name.capitalize()} wrapper initialized successfully")
        
    def _check_rate_limit(self):
        """Enforce rate limiting between requests."""
        elapsed = time.time() - self._last_request_time
        if elapsed < self.RATE_LIMIT:
            sleep_time = self.RATE_LIMIT - elapsed
            logger.debug(f"Rate limit active, sleeping {sleep_time:.2f}s")
            time.sleep(sleep_time)
            
    def _make_request(self, method: str, endpoint: str, **kwargs) -> Optional[Dict[str, Any]]:
        """
        Make an authenticated API request with error handling.
        
        Args:
            method: HTTP method (GET, POST, etc.)
            endpoint: API endpoint path
            **kwargs: Additional arguments for requests library
            
        Returns:
            Response data as dict if successful, None otherwise.
            
        Raises:
            ConnectionError: If network error occurs
            ValueError: If authentication fails or invalid response
        """
        url = f"{self.base_url}{endpoint}"
        
        headers = kwargs.pop('headers', {})
        headers['Authorization'] = f"Bearer {self.api_key}" if self.api_key else {}
        headers['Content-Type'] = 'application/json'
        
        try:
            self._check_rate_limit()
            
            response = requests.request(
                method=method,
                url=url,
                headers=headers,
                timeout=self.timeout,
                **kwargs
            )
            
            self.request_count += 1
            
            if response.status_code == 200:
                return response.json()
            elif response.status_code == 401:
                raise ValueError("Authentication failed. Check API key.")
            elif response.status_code == 429:
                logger.warning("Rate limit exceeded, waiting...")
                time.sleep(60)
                return self._make_request(method, endpoint, **kwargs)
            else:
                error_msg = f"API request failed with status {response.status_code}"
                logger.error(f"{error_msg}: {response.text}")
                raise ValueError(error_msg)
                
        except requests.exceptions.RequestException as e:
            self.last_error = str(e)
            logger.error(f"Request exception: {e}")
            return None
            
    def search(self, query: str, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Search the tool for data matching the query.
        
        Args:
            query: Search query string
            limit: Maximum number of results to return (default: 10)
            
        Returns:
            List of result objects from the API.
        """
        logger.info(f"Searching {tool_name} with query: {query}")
        
        data = self._make_request(
            "GET", 
            f"/search?q={query}&limit={min(limit, 100)}"
        )
        
        if data and isinstance(data, dict):
            results = data.get('results', []) or []
            logger.info(f"Found {len(results)} results")
            return results
            
        logger.warning("No results returned from search")
        return []
    
    def get_details(self, identifier: str) -> Optional[Dict[str, Any]]:
        """
        Get detailed information about a specific item.
        
        Args:
            identifier: Unique identifier for the resource
            
        Returns:
            Details dictionary or None if not found.
        """
        logger.info(f"Getting details for: {identifier}")
        
        data = self._make_request("GET", f"/details/{identifier}")
        
        return data if data else None
    
    def export_data(self, query: str, format_type: str = "json") -> Optional[Dict[str, Any]]:
        """
        Export search results in specified format.
        
        Args:
            query: Search query string
            format_type: Output format (json, csv, xml) - default: json
            
        Returns:
            Export data dictionary or None on failure.
        """
        logger.info(f"Exporting {tool_name} data in {format_type} format")
        
        data = self._make_request(
            "GET", 
            f"/export?q={query}&format={format_type}"
        )
        
        return data if data else None
    
    def health_check(self) -> bool:
        """
        Check API availability and authentication.
        
        Returns:
            True if API is accessible, False otherwise.
        """
        try:
            self._make_request("GET", "/health")
            logger.info(f"{tool_name.capitalize()} API is healthy")
            return True
        except Exception as e:
            logger.error(f"Health check failed: {e}")
            return False
    
    def reset_stats(self):
        """Reset request counters and error tracking."""
        self.request_count = 0
        self._last_request_time = time.time()
        self.last_error = None
        logger.debug("Stats reset")


# Example usage
if __name__ == "__main__":
    # Set your API key here or use environment variable
    import sys
    
    print("=" * 60)
    print(f"{tool_name.capitalize()} Wrapper - Test Mode")
    print("=" * 60)
    
    try:
        wrapper = {{ToolName}}Wrapper()
        
        if not wrapper.health_check():
            print("API health check failed!")
            sys.exit(1)
            
        # Run a test search
        results = wrapper.search(query="example.com", limit=5)
        print(f"\\nTest Search Results: {len(results)} items found")
        
        if results:
            print("\\nSample result:")
            import json
            print(json.dumps(results[0], indent=2))
            
    except Exception as e:
        print(f"Error during test: {e}")
        sys.exit(1)
    
    print("\\nWrapper generation complete!")
'''
        
        return wrapper_code
    
    def _extract_domain(self, url: str) -> str:
        """Extract domain from URL."""
        try:
            import re
            match = re.search(r'https?://([^/]+)', url)
            if match:
                return match.group(1)
        except Exception:
            pass
        return "unknown"


def generate_tool_wrapper(tool_name: str, api_url: str, api_key_env_var: str = None):
    """
    Convenience function to generate a tool wrapper.
    
    Args:
        tool_name: Name of the tool (will be used as filename and class name)
        api_url: Base URL of the API
        api_key_env_var: Environment variable name for API key (optional)
        
    Returns:
        str: Generated Python wrapper code
        
    Example usage:
        # Generate wrapper for a new tool
        code = generate_tool_wrapper(
            tool_name="whois_lookup",
            api_url="https://api.whois.com/v1",
            api_key_env_var="WHOIS_API_KEY"
        )
        
        # Save to file
        with open("whois_lookup_wrapper.py", "w") as f:
            f.write(code)
    """
    
    if not api_key_env_var:
        # Auto-generate env var name from tool name
        api_key_env_var = f"{tool_name.upper()}_API_KEY".replace("-", "_")
    
    generator = NewToolGenerator()
    return generator.generate_wrapper(tool_name, api_url, api_key_env_var)


def create_tool_file(tool_name: str, api_url: str, output_dir: str = ".", save: bool = True):
    """
    Generate and optionally save a tool wrapper to file.
    
    Args:
        tool_name: Name of the tool (filename will be {tool_name}_wrapper.py)
        api_url: Base URL of the API
        output_dir: Directory to save file (default: current directory)
        save: Whether to actually write the file
        
    Returns:
        str: Path to generated file if saved, otherwise None
    """
    
    import os
    
    # Determine env var name
    api_key_env_var = f"{tool_name.upper()}_API_KEY".replace("-", "_")
    
    # Generate code
    code = generate_tool_wrapper(tool_name, api_url, api_key_env_var)
    
    if save:
        filename = f"{tool_name}_wrapper.py"
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, "w") as f:
            f.write(code)
            
        print(f"✓ Generated wrapper: {filepath}")
        return filepath
    
    return None


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Generate Python wrapper for external tools",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate a new tool wrapper interactively
  python new_tool_generator.py --interactive
  
  # Generate wrapper for a specific tool
  python new_tool_generator.py --name shodan --url "https://api.shodan.io"
  
  # Save to custom directory
  python new_tool_generator.py --name mytool --url "https://api.example.com" --output ./wrappers/
        """
    )
    
    parser.add_argument(
        "--interactive", "-i", 
        action="store_true",
        help="Run in interactive mode to generate wrapper step by step"
    )
    
    parser.add_argument(
        "--name", "-n",
        type=str,
        default=None,
        help="Tool name (used for filename and class name)"
    )
    
    parser.add_argument(
        "--url", "-u",
        type=str,
        default=None,
        help="Base URL of the API"
    )
    
    parser.add_argument(
        "--output-dir",
        type=str,
        default=".",
        help="Directory to save generated wrapper file"
    )
    
    args = parser.parse_args()
    
    if args.interactive:
        print("=" * 60)
        print("New Tool Generator - Interactive Mode")
        print("=" * 60)
        
        tool_name = input("\\nTool name (e.g., shodan, whois): ").strip() or "new_tool"
        api_url = input("API base URL: ").strip() or "https://api.example.com/v1"
        
        save_file = input("\\nSave wrapper to file? [y/N]: ").strip().lower() == 'y'
        
        if save_file and args.output_dir != ".":
            import os
            os.makedirs(args.output_dir, exist_ok=True)
            
        filepath = create_tool_file(tool_name, api_url, args.output_dir, save=save_file)
        
        print("\\n" + "=" * 60)
        if filepath:
            print(f"Wrapper saved to: {filepath}")
            print("You can now use it in your harvesting pipeline!")
        else:
            code = generate_tool_wrapper(tool_name, api_url)
            print("\\nGenerated Code Preview:")
            print(code[:2000])  # Show first 2000 chars
        
    elif args.name and args.url:
        filepath = create_tool_file(args.name, args.url, args.output_dir)
        
        if filepath:
            print("✓ Wrapper generated successfully!")
            print(f"Usage in harvesting stage:")
            print(f"  from {args.name}_wrapper import {{ToolName}}Wrapper")
            print(f"  wrapper = {args.name.capitalize()}Wrapper()")
            
    else:
        parser.print_help()
